# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('synopsis', models.TextField(verbose_name='Sinopse')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor(a)')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='author',
        ),
        migrations.DeleteModel(
            name='Filmes',
        ),
    ]
